---

- name: Update homebrew itself first
  homebrew: update_homebrew=yes

- name: Install homebrew packages
  homebrew: name={{ item }}
  with_items:
    - git
    - gibo
    - zsh
    - tmux
    - reattach-to-user-namespace
    - ctags
    - rbenv
    - ruby-build
    - rbenv-gemset
    - pyenv
    - automake
    - pkg-config
    - mysql

- name: Add homebrew tap repositories
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - caskroom/cask

- name: Install Homebrew cask packages
  homebrew_cask: name={{ item }}
  with_items:
    - iterm2
    - atom
    - google-chrome
    - slack
    - caffeine
    - java
    - intellij-idea
    - phpstorm
    - webstorm
    - pycharm
    - datagrip
    - xquartz
    - mysqlworkbench
    - virtualbox
    - vagrant
    - mamp
    - docker

- name: Install homebrew packages
  homebrew: name={{ item }}
  with_items:
    - jenv
    - sbt
    - typesafe-activator
    - sanemat/font/ricty
    - memcached
    - redis
    - webkit2png
    - postgresql
    - lha
    - go
    - go-delve/delve/delve

- name: Install pip packages
  pip:
    name: fabric

- name: Clone dotfiles repository
  git:
    repo: https://github.com/yukihirai0505/dotfiles.git
    dest: "{{ ansible_env.HOME }}/dotfiles"

- name: Set up dotfiles
  shell: "sh {{ ansible_env.HOME }}/dotfiles/dotfilesLink.sh"

- name: Set local zsh
  become: true
  lineinfile:
    path: /etc/shells
    line: '/usr/local/bin/zsh'

- name: Change shell
  shell: 'chpass -s /usr/local/bin/zsh'

- name: Source .zshrc
  shell: 'source ~/.zshrc'

- name: Check ricty file
  stat:
    path: "{{ ansible_env.HOME }}/Library/Fonts/Ricty-Regular.ttf"
  register: ricty

- name: Copy ricty to Library
  shell: cp -f /usr/local/Cellar/ricty/*/share/fonts/Ricty*.ttf "{{ ansible_env.HOME }}/Library/Fonts/"
  when: not ricty.stat.exists

- name: Set up ricty
  shell: fc-cache -vf
  when: not ricty.stat.exists

- name: Clone neobundle repository
  git:
    repo: https://github.com/Shougo/neobundle.vim
    dest: "{{ ansible_env.HOME }}/.vim/neobundle.vim"
