---

- name: Update homebrew itself first
  homebrew: update_homebrew=yes

- name: Install homebrew packages
  homebrew: name={{ item }}
  with_items: "{{ homebrew_before_pkgs }}"

- name: Add homebrew tap repositories
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - caskroom/cask

- name: Update homebrew_cask itself first
  homebrew: update_homebrew=yes

- name: Install Homebrew cask packages
  homebrew_cask: name={{ item }}
  with_items: "{{ homebrew_cask_pkgs }}"

- name: Install homebrew packages
  homebrew: name={{ item }}
  with_items: "{{ homebrew_after_pkgs }}"
