---

- name: Check ricty file
  stat:
    path: "{{ ansible_env.HOME }}/Library/Fonts/Ricty-Regular.ttf"
  register: ricty

- name: Copy ricty to Library
  shell: cp -f /usr/local/Cellar/ricty/*/share/fonts/Ricty*.ttf "{{ ansible_env.HOME }}/Library/Fonts/"
  when: not ricty.stat.exists

- name: Set up ricty
  shell: fc-cache -vf
  when: not ricty.stat.exists
