---

- name: Clone dotfiles repository
  git:
    repo: https://github.com/yukihirai0505/dotfiles.git
    dest: "{{ ansible_env.HOME }}/dotfiles"

- name: Set up dotfiles
  shell: "sh {{ ansible_env.HOME }}/dotfiles/dotfilesLink.sh"

- name: Set local zsh
  become: true
  lineinfile:
    path: /etc/shells
    line: '/usr/local/bin/zsh'

- name: Check shell
  shell: 'echo `echo $SHELL | grep zsh | wc -l`'
  register: check_shell

- name: Change shell
  shell: 'chpass -s /usr/local/bin/zsh'
  when: check_shell.stdout == "0"

- name: Source .zshrc
  shell: 'source $HOME/.zshrc executable=/usr/local/bin/zsh'
